#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

wclean libso parcel
wclean libso phaseSystem
wclean libso interfacialModels
wclean libso momentumTransportModels
wclean libso thermophysicalTransportModels
wclean libso reactions
wclean libso phaseSystems

wclean

wclean libso fvModels
wclean libso functionObjects

#------------------------------------------------------------------------------
